### ISSUE TITLE
Unknown target shell in direnv 2.7.0

### ISSUE THREAD

**Issue by stobbsm** [rubymaniac/vscode-direnv#1]
Using this extension in VSCode, I get an error from direnv called "Unknown target shell".

Platform is Ubuntu 16.04, direnv 2.7.0

**Comment by stobbsm** [comment]
Just built direnv 2.10 from github, which has fixed it. It seem the Ubuntu package is to out of date to use the json shell type.

I'd suggest adding it to the documentation, as many developers will be using Ubuntu.

**Comment by rubymaniac** [comment]
Thanks for the feedback. I will add a notice for that.

**Comment by sjas** [comment]
upstream direnv version is still too old as of now. either compile from source as mentioned, or get a precompiled version from the releases page over at https://github.com/direnv/direnv/releases .
