### ISSUE TITLE
Error: direnv error: [31mdirenv: error Unknown target shell 'json'[0m

### ISSUE THREAD

**Issue by pckilgore** [rubymaniac/vscode-direnv#2]
Contents of my .envrc for this project is pretty simple:
`layout python3`

Let me know if/how to collect more information.

**Comment by rubymaniac** [comment]
What's your direnv version? (run `direnv version`)

Probably your version is < `2.8.0` and that is why it errors with `Unknown target shell 'json'`. Try to update direnv to the latest version.

This extension relies to the `direnv export json` command which got introduced at the `2.8.0` version.

**Comment by pckilgore** [comment]
Thanks! Xenial rolls with `2.7.0`, upgrading to `2.10.0` fixes the error message.
